server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true #解决options请求被拦截
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8090"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
      routes:
        - id: user-service
          uri: lb://user
          predicates:
            - Path=/user/**
  datasource:
    username: root
    password: wangzhibin
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aliyun.wzzz.shop:3306/hospita
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  data:
    redis:
      host: aliyun.wzzz.shop
      port: 6379
      username: wzb
      password: wangzhibin
      database: 0

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hnkjxy.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

wzzz:
  auth:
    secret: 23@#%atiqpa^&asvptjy*$
    expire: 604800 #7天
  url:
    white: /se